create table tag (
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table test (
    id int8 generated by default as identity,
    description varchar(255),
    img oid,
    level varchar(255),
    name varchar(255),
    question_count int4,
    tags_id int8,
    primary key (id)
);

create table test_progress_info (
    id int8 generated by default as identity,
    marker varchar(255),
    progress int4,
    result varchar(255),
    test_id int8,
    user_id int8,
    primary key (id)
);

create table theme (
    id int8 generated by default as identity,
    content oid,
    description varchar(255),
    number int4,
    theme varchar(255),
    type varchar(255),
    test_id int8,
    primary key (id)
);

create table user_role (
    user_id int8 not null,
    roles varchar(255)
);

create table user_tests (
    user_id int8 not null,
    test_id int8 not null
);

create table usr (
    id int8 generated by default as identity,
    avatar varchar(255),
    email varchar(255) not null,
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255) not null,
    phone varchar(255),
    primary key (id)
);

alter table if exists tag
    add constraint tag_name_uk
    unique (name);

alter table if exists usr
    add constraint usr_email_uk
    unique (email);

alter table if exists usr
    add constraint usr_phone_uk
    unique (phone);

alter table if exists test
    add constraint test_tags_id_fk
    foreign key (tags_id) references tag;

alter table if exists test_progress_info
    add constraint test_progress_info_test_id_fk
    foreign key (test_id) references test;

alter table if exists test_progress_info
    add constraint test_progress_info_user_id_fk
    foreign key (user_id) references usr;

alter table if exists theme
    add constraint theme_test_id_fk
    foreign key (test_id) references test;

alter table if exists user_role
    add constraint user_role_user_id_fk
    foreign key (user_id) references usr;

alter table if exists user_tests
    add constraint user_tests_test_id_fk
    foreign key (test_id) references test;

alter table if exists user_tests
    add constraint user_tests_user_id_fk
    foreign key (user_id) references usr;